--TABLE: LABORATORIO
CREATE TABLE LABORATORIO(
    ID_LAB INTEGER PRIMARY KEY,
    NOME VARCHAR2(50) NOT NULL,
    DESCRIZIONE VARCHAR2(250) DEFAULT 'Descrizione non presente' NOT NULL 
);
--GENERATORE DI ID--
CREATE SEQUENCE genera_lab_id
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

--TABLE: SEDE
CREATE TABLE SEDE(
    ID_SEDE INTEGER PRIMARY KEY,
    INDIRIZZO VARCHAR2(100) NOT NULL,
    CAMPO VARCHAR2(50) DEFAULT 'Sconosciuto',
    ANNOFONDAZIONE NUMBER(4, 0),
    ID_LAB INTEGER NOT NULL,
--FOREIGN KEY
    CONSTRAINT sede_fk FOREIGN KEY (ID_LAB) REFERENCES LABORATORIO(ID_LAB) ON DELETE CASCADE
);
--GENERATORE DI ID--
CREATE SEQUENCE genera_sede_id
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOCACHE;    
  